services:
  db:
    image: postgres:15
    container_name: goodhamburger-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GoodHamburger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: goodhamburger-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: GoodHamburger.API/Dockerfile
    container_name: goodhamburger-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=GoodHamburger;Username=postgres;Password=postgres
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: GoodHamburger.Web/Dockerfile
    container_name: goodhamburger-web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
